[build]
builder = "dockerfile"
dockerfilePath = "./Bot/Dockerfile"

[deploy]
startCommand = "python main_fixed_final.py"

[[build.watchPatterns]]
pattern = "Bot/**"

[[build.watchPatterns]]
pattern = "requirements.txt"
